name: Deploy Production

on:
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy-tg-bot.yml
    with:
      vercel_production: true
      environment_name: production
    secrets:
      MONGODB_URI: ${{ secrets.PROD_MONGODB_URI }}
      BOT_TOKEN: ${{ secrets.PROD_BOT_TOKEN }}
      WEBHOOK_SECRET: ${{ secrets.PROD_WEBHOOK_SECRET }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
