name: Deploy Staging

on:
  push:
    branches: [develop]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy-tg-bot.yml
    secrets:
      MONGODB_URI: ${{ secrets.STAGING_MONGODB_URI }}
      BOT_TOKEN: ${{ secrets.STAGING_BOT_TOKEN }}
      WEBHOOK_SECRET: ${{ secrets.STAGING_WEBHOOK_SECRET }}
